# Generated by Django 4.0.3 on 2022-04-11 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do módulo')),
                ('description', models.CharField(max_length=1500, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da aula')),
                ('description', models.CharField(max_length=1500, verbose_name='Descrição')),
                ('date_class', models.DateField(verbose_name='Data da aula')),
                ('duration', models.IntegerField(verbose_name='Duração')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codeflix.module', verbose_name='Módulo')),
            ],
        ),
    ]
